# Generated by Django 5.0 on 2024-10-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heladera',
            name='latitud',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
        migrations.AlterField(
            model_name='heladera',
            name='longitud',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
    ]
